version: '3'
services: 
  database:
    image: 'mongo'
    container_name: 'mongodb-server'
    environment: 
      - MONGO_INITDB_DATABASE=petgram
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-db.js:ro
      - ./.data:/data/db
    ports:
      - 27017:27017
